#cloud-config

# Add apt source
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

# Install these packages
packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

# Allow default user to use docker
system_info:
  default_user:
    groups: [docker]
